### ISSUE TITLE
Request: make arrays in the spec `readonly`

### ISSUE THREAD

**Issue by ahrjarrett** [standard-schema/standard-schema#2]
Hello!

I've been waiting for something like `standard-schema` to come around. This proposal seems well thought out, so I'm looking forward to tracking its adoption.

The `~` prefix, in particular, is a great touch.

One potential issue I see is with the standard defaulting to mutable arrays.

Would this proposal be open to using readonly arrays throughout, instead? That way the spec supports both use cases.

Especially with `as const` and the `const` type parameter in TS v5.0, I imagine this issue will crop up eventually, so hopefully we can avoid that problem at the outset :)

**Comment by colinhacks** [comment]
Closed in https://github.com/standard-schema/standard-schema/commit/4bc93f06e9dfc143c7ccfe824ea2d436eeeaa084
