### ISSUE TITLE
How to validate a ValidationError

### ISSUE THREAD

**Issue by mmkal** [standard-schema/standard-schema#4]
Since we're returning a non-discriminated union, does that make it impossible for a standard-schema lib to validate a `ValidationError` instance? If so, or if there's some intended workaround I think it'd be worth noting. 

https://github.com/standard-schema/standard-schema?tab=readme-ov-file#why-not-use-a-discriminated-union

**Comment by mmkal** [comment]
I'm thinking more of a case where you want to check an unknown object to see whether it's a well-defined `ValidationError` itself. If you tried to use `schema['~validate](input)` you would never know if the result had the `~validationerror` property because the input object had it, or because it didn't conform to `ValidationError` properly. Wouldn't that be a problem however it's spelled, and whether it's a string or a symbol?

**Comment by colinhacks** [comment]
Yeah that's what I'm trying to say in my first comment 👇

> Technically a conflict is possible with a parse result containing that same property...definitely open to changing this to something even more obscure.

I just don't think it really matters if we pick a sufficiently obscure key.

**Comment by mmkal** [comment]
Maybe I'm still misunderstanding. Let's say trpc adopts standard-schema. The updated [`getParseFunction`](https://github.com/trpc/trpc/blob/main/packages/server/src/unstable-core-do-not-import/parser.ts#L70) implementation in trpc would probably need to look something like this:

```ts
export function getParseFn<TType>(procedureParser: Parser): ParseFn<TType> {
  const parser = procedureParser as any;

  if (typeof parser === 'function') {
    // ParserCustomValidatorEsque
    return parser;
  }

  if (typeof parser.parse === 'function') {
    // ParserZodEsque
    // ParserValibotEsque (< v0.13.0)
    return parser.parse.bind(parser);
  }

  if (typeof parser.validateSync === 'function') {
    // ParserYupEsque
    return parser.validateSync.bind(parser);
  }

  // more libraries...

  if (typeof parser['~validate'] === 'function') {
    // ParserStandardSchemaEsque
    return (input: unknown) => {
      const result = parser['~validate'](input)
      if (input['~validationerror']) throw result
      return result
    }
  }
  

  throw new Error('Could not find a validator fn');
}
```

So if I was writing a very valuable API that takes standard schema validation errors and turns them into nice human readable strings, I might do something like this:

```ts
import {standardSchema as s} from 'zod'

t.router({
  errorToString: t
    .input(s.object({ '~validationError': s.literal(true), issues: s.array(s.any()) }))
    .query(({input}) => input.issues.map(iss => JSON.stringify(iss).join('\n'))
```

I think tRPC would always respond 400 for this procedure, even if you pass it the input it's expecting.

---

I had written the above before 0551115776785340ab3270fc796731d500a2b7e5 - which maybe improves things a bit? Is the idea that instead of the above tRPC wrapper would do something more like this?

```ts
return (input: unknown) => {
  const result = parser['~validate'](input)
  if (result.issues) throw result
  return result.value
}
```

**Comment by mmkal** [comment]
I agree with the above, I don't see it as a bad thing at all. Was just wondering if worth noting in the docs, but no longer relevant now.

**Comment by artalar** [comment]
Hi there! I am not sure about the end profit of this spec. I think it should be simple for an end user to receive a structured error message from any validation library. Currently, this is not handled in the specification. What I would like to see is a `getErrors()` method in the spec package itself (which can be exported by each library) that accepts an error object (`any`) and does something like this: `thing => thing instanceof Error && '~standardV1' in thing ? JSON.parse(thing.message) : undefined`.
