### ISSUE TITLE
RFC: Self-documentation (Option 2)

### ISSUE THREAD

**Issue by colinhacks** [standard-schema/standard-schema#5]
The [initial proposal](https://github.com/standard-schema/standard-schema) described a standard interface that could be implemented by all schema/validation libraries to support better interoperability. This would require all schemas to implement a method called `~validate`.

There were concerns from some library authors about bundle size, since this would require additional code. 

This new proposal aims to address that concern by allowing schema/validator to *self-document* their own methods and return types. It assumes that any given schema/validator has a method with the following general signature:

```ts
interface ValidatorInput<T> = T | { [input_key]: T };

interface Validator<T> {
  [validate_key](input: ValidatorInput<T>, ...args: any[]):
    | { [success_key]: true, [data_key]: T } 
    | { [success_key]: false, [error_key]: ValidationError }
}

interface ValidationError {
  [issues_key]: Array<{ 
    [path_key]: Array<{ [key_key]: PropertyKey } | PropertyKey>,
    [message_key]: string
  }>
}
```

The idea is for libraries to *self document* the values for the various keys by conforming to this interface:

```ts
interface StandardSchema<Out extends string = "output", In extends string = "input"> {
  "~s~": {
    // self-documentation
    in?: string | null; // input_key (default "input", null means the input is passed directly)
    v?: string; // validate_key (default "_run")
    s?: string; // success_key (default "typed")
    d?: string; // data_key (default "value")
    e?: string; // error_key (default "error")
    is?: string | null; // issues_key (default "issues")
    p?: string; // path_key (default "path")
    m?: string; // message_key (default "message")
    k?: "key";
    
    // for inferred types (don't need to exist at runtime)
    $o: Out; // output_key (default "output")
    $i: In; // input_key (default "input")
  }
}
```

A consuming library can accept a compliant schema, check for the `~s~` key, and read the fields to know how to use the schema to parse data & interpret the results.

## Worked example

For Zod to conform to this proposal it would need to add the following to its base class `ZodType`:

```ts
class ZodType {
  "~s~" = {
    v: "safeParse",
    d: "value"
  } as StandardSchema<"_output", "_input">["~s~"];
}
```

In terms of runtime bundle size, this would only increase bundle size by 35 bytes. 

---

Very open to changing the default values of each key to whatever value minimizes the bundle size increase for the greatest set of libraries!

**Comment by ssalbdivad** [comment]
Interesting. The main thing I'd be concerned about here is adding additional inference overhead. My intuition is the type perf is going to be more relevant to most developers than bundle size here, but maybe I'm underestimating the impact the original proposal would have on bundle size for other libraries.
